CREATE DATABASE `omg`;

USE `omg`;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `email` VARCHAR(320) NOT NULL UNIQUE,
    `username` VARCHAR(10) NOT NULL,
    `password` VARCHAR(60) NOT NULL,
    `phone` VARCHAR(20) NOT NULL UNIQUE
) CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `board`;
CREATE TABLE `board` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `date` DATETIME NOT NULL DEFAULT NOW(),
    `title` VARCHAR(100) NOT NULL,
    `content` MEDIUMTEXT NOT NULL
) CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE USER 'wink'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';
GRANT ALL PRIVILEGES ON omg.* TO 'wink'@'localhost' WITH GRANT OPTION;